# Generated by Django 3.2.8 on 2021-11-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news_letters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('project_description', models.CharField(max_length=1000)),
                ('project_image', models.CharField(max_length=1000)),
                ('project_link', models.CharField(max_length=200)),
            ],
        ),
    ]
