# Generated by Django 3.2.8 on 2021-11-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='news_letters',
            new_name='projects',
        ),
    ]
