# Generated by Django 3.2.8 on 2021-11-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_news_letters_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_image',
            field=models.FilePathField(max_length=1000),
        ),
    ]
