# Generated by Django 3.2.8 on 2021-11-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_projects_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_image',
            field=models.CharField(max_length=1000),
        ),
    ]
